apiVersion: v1
kind: Service
metadata:
  name: api-test-back-v1
  namespace: api-test-ns
  labels:
      app: api-test-back
      version: v1
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
      app: api-test-back
      version: v1
